name: CD

concurrency: production

on:
  workflow_run:
      workflows: ["CI"]
      branches:
        - main
        - 'releases/**'
      types: 
        - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: weipu
          path: |
            dist
            !dist/**/*.md
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: weipu
          path: dist
          retention-days: 5
      
