name: CD

concurrency: production

on:
  workflow_run:
    workflows: ['CI']
    branches:
      - main
      - 'releases/**'
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@main

      - name: Show the next version
        run: |
          echo ${{ steps.get_next_version.outputs.version }}
          echo ${{ steps.get_next_version.outputs.hasNextVersion }}

      - name: Upload weipu via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: '.,!.git,!.github'
          target: '/home/weipu/download/artifacts/${{ steps.get_next_version.outputs.version }}'

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            mkdir -p /home/weipu/www/weipu2
            rm -rf /home/weipu/www/weipu2/*
            cp -a /home/weipu/download/artifacts/${{ steps.get_next_version.outputs.version }}/* /home/weipu/www/weipu2/
            npm --prefix /home/weipu/www/weipu2/ install
            npm --prefix /home/weipu/www/weipu2/ run build
            sudo systemctl restart weipu2
