name: CD

concurrency: production

on:
  workflow_run:
      workflows: ["CI"]
      branches:
        - main
        - 'releases/**'
      types: 
        - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: weipu
          path: |
            .
            !.git
          
      - name: Download weipu artifact
        uses: actions/download-artifact@v3
        with:
          name: weipu
          path: ${{ github.run_number }}

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: mkdir /home/weipu/download/artifacts/${{ github.run_number }}
          
      - name: Upload weipu artifact via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: ${{ github.run_number }}
          target: "/home/weipu/download/artifacts/${{ github.run_number }}"
